openapi: "3.0.0"
info:
  title: myAPI
  version: "1.0"
servers:
  - url: http://localhost:8000
paths:
  /:
    get:
      summary: myAPI
      description: This is myAPI
      operationId: hello.post_greeting
      responses:
        200:
          description: the response
          content:
            text/plain:
              schema:
                type: string
                example: "hello from myAPI!"
